# Generated by Django 5.1.5 on 2025-01-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActuatorControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_led_choice', models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=0)),
                ('heater_led_choice', models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=0)),
                ('fan_choice', models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=0)),
                ('servo_motor_choice', models.IntegerField(choices=[(0, 'Locked'), (1, 'Unlocked')], default=0)),
                ('main_led_status', models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=0)),
                ('heater_led_status', models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=0)),
                ('fan_status', models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=0)),
                ('servo_motor_status', models.IntegerField(choices=[(0, 'Locked'), (1, 'Unlocked')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('brightness', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ThresholdSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_threshold_min', models.FloatField(default=18.0)),
                ('temperature_threshold_max', models.FloatField(default=30.0)),
                ('humidity_threshold_min', models.FloatField(default=30.0)),
                ('humidity_threshold_max', models.FloatField(default=60.0)),
                ('brightness_threshold_min', models.FloatField(default=200)),
            ],
        ),
    ]
