# Generated by Django 5.1.5 on 2025-01-20 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actuatorcontrol',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sensordata',
            options={'managed': False},
        ),
    ]
